# Type stubs for aiohttp
from typing import Any
from types import TracebackType

class ClientTimeout:
    def __init__(self, total: float | None = None, connect: float | None = None) -> None: ...
    total: float | None

class ClientResponse:
    status: int
    async def text(self) -> str: ...
    async def json(self) -> dict[str, Any]: ...
    def raise_for_status(self) -> None: ...
    async def __aenter__(self) -> "ClientResponse": ...
    async def __aexit__(self, exc_type: type[BaseException] | None, exc_val: BaseException | None, exc_tb: TracebackType | None) -> None: ...

class ClientSession:
    def __init__(self, timeout: ClientTimeout | None = None, headers: dict[str, str] | None = None) -> None: ...
    def get(self, url: str, headers: dict[str, str] | None = None) -> ClientResponse: ...
    async def __aenter__(self) -> "ClientSession": ...
    async def __aexit__(self, exc_type: type[BaseException] | None, exc_val: BaseException | None, exc_tb: TracebackType | None) -> None: ...

class ClientError(Exception):
    pass
