"""Type stubs for selenium.webdriver.remote.webdriver"""

from typing import Any
from selenium.webdriver.remote.webelement import WebElement
from selenium.webdriver.common.by import By

class WebDriver:
    @property
    def title(self) -> str: ...
    
    @property
    def current_url(self) -> str: ...
    
    @property
    def page_source(self) -> str: ...
    
    def get(self, url: str) -> None: ...
    
    def find_element(self, by: str, value: str) -> WebElement: ...
    
    def find_elements(self, by: str, value: str) -> list[WebElement]: ...
    
    def save_screenshot(self, filename: str) -> bool: ...
    
    def quit(self) -> None: ...
    
    def close(self) -> None: ...
