"""Type stubs for selenium.webdriver.remote.webelement"""

from typing import Any

class WebElement:
    @property
    def text(self) -> str: ...
    
    @property
    def tag_name(self) -> str: ...
    
    def get_attribute(self, name: str) -> str | None: ...
    
    def find_element(self, by: str, value: str) -> "WebElement": ...
    
    def find_elements(self, by: str, value: str) -> list["WebElement"]: ...
    
    def click(self) -> None: ...
    
    def send_keys(self, *value: str) -> None: ...
    
    def is_displayed(self) -> bool: ...
