# Selenium type stubs for WebDriver elements
# EMD Compliance: ≤80 lines

from typing import Any

class WebElement:
    """Type stub for Selenium WebElement"""
    text: str
    
    def find_element(self, by: Any, value: str) -> "WebElement": ...
    def find_elements(self, by: Any, value: str) -> list["WebElement"]: ...
    def get_attribute(self, name: str) -> str | None: ...
    def click(self) -> None: ...
    def send_keys(self, *value: Any) -> None: ...
    def clear(self) -> None: ...
    def is_displayed(self) -> bool: ...
    def is_enabled(self) -> bool: ...
    def is_selected(self) -> bool: ...

class WebDriver:
    """Type stub for Selenium WebDriver"""
    
    def get(self, url: str) -> None: ...
    def find_element(self, by: Any, value: str) -> WebElement: ...
    def find_elements(self, by: Any, value: str) -> list[WebElement]: ...
    def execute_script(self, script: str, *args: Any) -> Any: ...
    def quit(self) -> None: ...
    def close(self) -> None: ...
